#mapper
#mappers 多个接口时逗号隔开
mapper:
    identity: MYSQL
    mappers: tk.mybatis.mapper.common.Mapper
    not-empty: false
#pagehelper
pagehelper:
    helperDialect: mysql
    params: count=countSql
    reasonable: true
    supportMethodsArguments: true
#management
management:
  endpoint:
    health:
      show-details: always
